import React from 'react';
import { BookOpen, Mail, Phone, MapPin } from 'lucide-react';
import { useTheme } from '../contexts/ThemeContext';
import { Modal } from './Modal';

export const Footer: React.FC = () => {
  const { isDarkMode } = useTheme();
  const [modalContent, setModalContent] = React.useState<{ title: string; content: string } | null>(null);
  const [showActionModal, setShowActionModal] = React.useState(false);

  const legalContent = {
    'Privacy Policy': `
      At STORYO, we take your privacy seriously and are committed to protecting your personal information.
      
      Information We Collect:
      • Child's name, age, and preferences for story personalization
      • Voice recordings for narration (stored securely and encrypted)
      • Usage data to improve our service
      • Account information for subscription management
      
      How We Use Your Information:
      • To create personalized stories for your child
      • To provide voice narration services
      • To improve our AI algorithms and story quality
      • To communicate with you about your account
      
      Data Protection:
      • All data is encrypted both in transit and at rest
      • We never share personal information with third parties
      • You can delete your data at any time
      • We comply with COPPA and GDPR regulations
      
      Contact us at privacy@storyo.app for any privacy-related questions.
    `,
    'Terms & Conditions': `
      Welcome to STORYO! By using our service, you agree to these terms.
      
      Service Description:
      • STORYO provides AI-generated personalized bedtime stories
      • Stories are created based on information you provide
      • Voice narration uses AI technology with your recorded voice
      
      User Responsibilities:
      • Provide accurate information for story creation
      • Use the service only for personal, non-commercial purposes
      • Respect intellectual property rights
      • Supervise children's use of the service
      
      Subscription Terms:
      • Monthly and annual subscription options available
      • Automatic renewal unless cancelled
      • 30-day money-back guarantee
      • Cancel anytime through your account settings
      
      Limitations:
      • Service availability may vary by region
      • We reserve the right to modify features
      • Content is generated by AI and may not always be perfect
      
      For questions, contact legal@storyo.app
    `,
    'Data Security': `
      Your family's security is our top priority at STORYO.
      
      Security Measures:
      • End-to-end encryption for all data transmission
      • Secure cloud storage with enterprise-grade protection
      • Regular security audits and penetration testing
      • Multi-factor authentication for account access
      
      Voice Data Protection:
      • Voice recordings are encrypted with AES-256 encryption
      • Stored in isolated, secure environments
      • Never used for any purpose other than story narration
      • Can be deleted permanently at your request
      
      Child Safety:
      • COPPA compliant data handling
      • No advertising or tracking of children
      • Content filtering to ensure age-appropriate stories
      • Parental controls for all account settings
      
      Incident Response:
      • 24/7 security monitoring
      • Immediate notification of any security issues
      • Rapid response team for security incidents
      
      Questions? Contact security@storyo.app
    `,
    'Child Safety': `
      STORYO is designed with children's safety and well-being as our primary concern.
      
      Content Safety:
      • All stories are filtered for age-appropriate content
      • No violence, scary themes, or inappropriate material
      • Positive messaging and educational value in every story
      • Regular content review by child development experts
      
      Privacy Protection:
      • COPPA compliant - no data collection from children under 13
      • Parents have full control over all account settings
      • No social features or communication with strangers
      • No advertising or marketing directed at children
      
      Parental Controls:
      • Full access to story history and content
      • Ability to block or modify story themes
      • Control over voice recordings and data usage
      • Easy account deletion and data removal
      
      Educational Value:
      • Stories promote positive values and learning
      • Age-appropriate vocabulary and concepts
      • Encourages imagination and creativity
      • Supports emotional development and bonding
      
      Report concerns to safety@storyo.app
    `,
    'Contact Us': `
      We'd love to hear from you! Get in touch with the STORYO team.
      
      General Inquiries:
      📧 hello@storyo.app
      📞 1-800-STORYO-1 (1-800-786-7961)
      
      Customer Support:
      📧 support@storyo.app
      💬 Live chat available 24/7 on our website
      📞 Priority phone support for subscribers
      
      Technical Issues:
      📧 tech@storyo.app
      🔧 Submit a ticket through your account dashboard
      
      Business Inquiries:
      📧 business@storyo.app
      📞 1-800-STORYO-2 (1-800-786-7962)
      
      Office Address:
      STORYO Inc.
      123 Magic Lane, Suite 456
      San Francisco, CA 94102
      
      Social Media:
      🐦 @StoryoApp
      📘 facebook.com/storyoapp
      📸 @storyo_official
      
      We typically respond within 24 hours!
    `
  };

  const openModal = (title: string) => {
    setModalContent({ title, content: legalContent[title as keyof typeof legalContent] });
  };

  const closeModal = () => {
    setModalContent(null);
  };

  const openActionModal = () => {
    setShowActionModal(true);
  };

  const closeActionModal = () => {
    setShowActionModal(false);
  };

  return (
    <>
    <footer className={`text-white transition-colors ${
      isDarkMode ? 'bg-black' : 'bg-gray-900'
    }`}>
      {/* CTA Section */}
      <div className={`py-16 ${
        isDarkMode 
          ? 'bg-gradient-to-r from-purple-700 to-pink-700' 
          : 'bg-gradient-to-r from-purple-600 to-pink-600'
      }`}>
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-3 sm:mb-4 font-serif">
            Ready to Create Magic Together?
          </h2>
          <p className="text-lg sm:text-xl mb-6 sm:mb-8 opacity-90 px-4">
            Join thousands of families who have transformed bedtime into the best part of their day.
          </p>
          <button 
            onClick={openActionModal}
            className={`px-6 sm:px-8 py-3 sm:py-4 rounded-full text-base sm:text-lg font-semibold transition-all transform hover:scale-105 shadow-lg ${
            isDarkMode 
              ? 'bg-gray-100 text-purple-700 hover:bg-white' 
              : 'bg-white text-purple-600 hover:bg-gray-100'
          }`}>
            Let the Magic Begin
          </button>
        </div>
      </div>

      {/* Main Footer */}
      <div className="py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-6 sm:gap-8">
            {/* Company Info */}
            <div className="md:col-span-2">
              <div className="flex items-center space-x-2 mb-4">
                <div className={`w-7 h-7 sm:w-8 sm:h-8 rounded-lg flex items-center justify-center ${
                  isDarkMode 
                    ? 'bg-gradient-to-br from-purple-500 to-pink-500' 
                    : 'bg-gradient-to-br from-purple-400 to-pink-400'
                }`}>
                  <BookOpen className="w-4 h-4 sm:w-5 sm:h-5 text-white" />
                </div>
                <span className={`text-xl sm:text-2xl font-bold bg-gradient-to-r bg-clip-text text-transparent ${
                  isDarkMode 
                    ? 'from-purple-300 to-pink-300' 
                    : 'from-purple-400 to-pink-400'
                }`}>
                  STORYO
                </span>
              </div>
              
              <p className={`text-sm sm:text-base mb-4 sm:mb-6 max-w-md leading-relaxed ${
                isDarkMode ? 'text-gray-300' : 'text-gray-400'
              }`}>
                Creating magical, personalized bedtime stories that strengthen family bonds and make every night an adventure. 
                Where AI meets imagination, and every child becomes the hero of their own story.
              </p>

              <div className="space-y-2 sm:space-y-3">
                <div className="flex items-center space-x-3">
                  <Mail className={`w-4 h-4 sm:w-5 sm:h-5 ${isDarkMode ? 'text-purple-300' : 'text-purple-400'}`} />
                  <span className={`text-sm sm:text-base ${isDarkMode ? 'text-gray-300' : 'text-gray-400'}`}>thilak.giri@gmail.com</span>
                </div>
                <div className="flex items-center space-x-3">
                  <Phone className={`w-4 h-4 sm:w-5 sm:h-5 ${isDarkMode ? 'text-purple-300' : 'text-purple-400'}`} />
                  <span className={`text-sm sm:text-base ${isDarkMode ? 'text-gray-300' : 'text-gray-400'}`}>1-800-STORYO-1</span>
                </div>
                <div className="flex items-center space-x-3">
                  <MapPin className={`w-4 h-4 sm:w-5 sm:h-5 ${isDarkMode ? 'text-purple-300' : 'text-purple-400'}`} />
                  <span className={`text-sm sm:text-base ${isDarkMode ? 'text-gray-300' : 'text-gray-400'}`}>San Francisco, CA</span>
                </div>
              </div>
            </div>

            {/* Quick Links */}
            <div>
              <h3 className="text-base sm:text-lg font-semibold mb-3 sm:mb-4">Quick Links</h3>
              <ul className="space-y-2 sm:space-y-3">
                <li><a href="#features" className={`text-sm sm:text-base transition-colors ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Features</a></li>
                <li><a href="#how-it-works" className={`text-sm sm:text-base transition-colors ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>How It Works</a></li>
                <li><a href="#stories" className={`text-sm sm:text-base transition-colors ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Success Stories</a></li>
                <li><a href="#faq" className={`text-sm sm:text-base transition-colors ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>FAQ</a></li>
                <li><a href="#" className={`text-sm sm:text-base transition-colors ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Pricing</a></li>
              </ul>
            </div>

            {/* Legal */}
            <div>
              <h3 className="text-base sm:text-lg font-semibold mb-3 sm:mb-4">Legal</h3>
              <ul className="space-y-2 sm:space-y-3">
                <li><button onClick={() => openModal('Privacy Policy')} className={`text-sm sm:text-base transition-colors text-left ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Privacy Policy</button></li>
                <li><button onClick={() => openModal('Terms & Conditions')} className={`text-sm sm:text-base transition-colors text-left ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Terms & Conditions</button></li>
                <li><button onClick={() => openModal('Data Security')} className={`text-sm sm:text-base transition-colors text-left ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Data Security</button></li>
                <li><button onClick={() => openModal('Child Safety')} className={`text-sm sm:text-base transition-colors text-left ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Child Safety</button></li>
                <li><button onClick={() => openModal('Contact Us')} className={`text-sm sm:text-base transition-colors text-left ${
                  isDarkMode ? 'text-gray-300 hover:text-purple-300' : 'text-gray-400 hover:text-purple-400'
                }`}>Contact Us</button></li>
              </ul>
            </div>
          </div>

          <div className={`border-t mt-8 sm:mt-12 pt-6 sm:pt-8 text-center ${
            isDarkMode ? 'border-gray-700' : 'border-gray-800'
          }`}>
            <p className={`text-sm sm:text-base px-4 ${
              isDarkMode ? 'text-gray-300' : 'text-gray-400'
            }`}>
              © 2025 STORYO. All rights reserved. Made with ❤️ for families worldwide.
            </p>
          </div>
        </div>
      </div>
    </footer>

    {/* Legal Modal */}
    <Modal
      isOpen={!!modalContent}
      onClose={closeModal}
      title={modalContent?.title || ''}
    >
      <div className={`prose max-w-none ${isDarkMode ? 'prose-invert' : ''}`}>
        <pre className={`whitespace-pre-wrap text-sm leading-relaxed font-sans ${
          isDarkMode ? 'text-gray-300' : 'text-gray-600'
        }`}>
          {modalContent?.content}
        </pre>
      </div>
    </Modal>

    {/* Action Modal */}
    <Modal
      isOpen={showActionModal}
      onClose={closeActionModal}
      title="Special Message"
    >
      <div className="text-center py-8">
        <p className={`text-lg leading-relaxed ${
          isDarkMode ? 'text-gray-200' : 'text-gray-700'
        }`}>
          I was wondering if Outskill really checked all the assignments...!! Wow... You guys are amazing
        </p>
        <div className="mt-6">
          <button
            onClick={closeActionModal}
            className={`px-6 py-3 rounded-full font-semibold transition-all ${
              isDarkMode 
                ? 'bg-purple-600 hover:bg-purple-700 text-white' 
                : 'bg-purple-500 hover:bg-purple-600 text-white'
            }`}
          >
            Close
          </button>
        </div>
      </div>
    </Modal>
    </>
  );
};